pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Instalar dependencias') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }

        stage('Tests') {
            agent {
    docker {
      image 'python:3.6-slim'
    }
  }
            steps {
                sh 'pytest -q'
            }
        }
       stage('Info'){
            steps{ 
                  echo "Job: ${env.JOB_NAME}"
                  echo "Build ${env.BUILD_NUMBER}"

               }
               }
    }
}


