pipeline {
    agent  { docker { image 'python:3.10-slim' } }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Instalar dependencias') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }

        stage('Tests') {
            steps {
                sh 'pytest -q'
            }
        }

        stage('Info') {
            steps { 
                echo "Job: ${env.JOB_NAME}"
                echo "Build: ${env.BUILD_NUMBER}" 
            }
        }
// ejercicio 2
        stage('Python Test') {
    agent {
        docker {
            image 'python:3.6-slim'
        }
    }
    steps {
        sh 'pip install -r requirements.txt'
        sh 'pytest -q'
    }
}

    }
}

